version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 99
    reviewers:
      - dadoonet
    assignees:
      - dadoonet
    labels:
      - dependencies
    milestone: 22

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 99
    reviewers:
      - dadoonet
    assignees:
      - dadoonet
    labels:
      - dependencies
    milestone: 22
