# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Build and Deploy the main branch
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Create Maven settings.xml
      uses: s4u/maven-settings-action@v3.1.0
      with:
        githubServer: false
        servers: '[{"id": "central", "username": "${{ secrets.CENTRAL_USERNAME }}", "password": "${{ secrets.CENTRAL_TOKEN }}"}]'
    - name: Deploy with Maven
      run: mvn deploy -DskipTests
